//import 'chapter_db.dart';
import 'dart:convert';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
/// The data associated with users.
part 'user_db.freezed.dart';
part 'user_db.g.dart';

@freezed
class UserData with _$UserData {
  const factory UserData({
    required String name,
    required String email,
    required String imagePath,
    required String bio,
    // required bool isOnline,
    // required DateTime lastActive,
  }) = _UserData; // This line is automatically generated by freezed

  factory UserData.fromJson(Map<String, dynamic> json) => _$UserDataFromJson(json);

  static Future<List<UserData>> checkInitialData() async {
    String content =
    await rootBundle.loadString("assets/initialData/Users.json");
    List<dynamic> initialData = json.decode(content);
    return initialData.map((jsonData) => UserData.fromJson(jsonData)).toList();
  }
}

// class UserRepository {
//   UserData getUser(String userID) {
//     return _users.firstWhere((userData) => userData.id == userID);
//   }
//
//   String getUserName(String userID) {
//     return _users.firstWhere((userData) => userData.id == userID).name;
//   }
//
//   String getUserImagePath(String userID) {
//     return _users.firstWhere((userData) => userData.id == userID).imagePath;
//   }
//
//   bool isUserEmail(String email) {
//     List<String> emails = _users.map((userData) => userData.email).toList();
//     return emails.contains(email);
//   }
//
//   String getUserIDByEmail(String email) {
//     return _users.firstWhere((userData) => userData.email == email).id;
//   }
//
// }
// List<UserData> _users = [
//   UserData(
//       id: 'user-001',
//       name: 'Rahat',
//       email: 'rahat@gmail.com',
//       isOnline: true,
//       lastActive: DateTime.now(),
//       imagePath: 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=DRMNtvMAAAAJ&citpid=2',
//       bio: 'I am a computer science masters student at UHManoa'),
//   UserData(
//       id: 'user-002',
//       name: 'Armin',
//       email: 'asoltan@hawaii.edu',
//       isOnline: true,
//       lastActive: DateTime.now(),
//       imagePath: 'https://hawaiidigitalhealthlab.com/content/images/2023/06/armin.jpeg',
//       bio: 'I am passionate about mobile application development'),
//   UserData(
//       id: 'user-003',
//       name: 'John',
//       email: 'john@gmail.com',
//       isOnline: true,
//       lastActive: DateTime.now(),
//       imagePath: 'https://raw.githubusercontent.com/philipmjohnson/philipmjohnson.github.io/main/img/pmj-headshot.png',
//       bio: 'I am passionate about teaching people about mobile apps'),
// ];
/// Provides access to and operations on all defined users.

/// The singleton instance providing access to all user data for clients.
// UserData userDB = UserData();
