// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIl8kmgaz0hwtswyxZm3C_dguwDgkGYs',
    appId: '1:402862399682:web:1090a89c86f6aca02c1b5b',
    messagingSenderId: '402862399682',
    projectId: 'uhmschoolbook',
    authDomain: 'uhmschoolbook.firebaseapp.com',
    storageBucket: 'uhmschoolbook.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75zx0pTXh6vWekg7KndEkK5Wi94_uYDQ',
    appId: '1:402862399682:android:87168739a81d09e02c1b5b',
    messagingSenderId: '402862399682',
    projectId: 'uhmschoolbook',
    storageBucket: 'uhmschoolbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo32IrxGuT9PeplBjSLfpjBKb2cJ9wFls',
    appId: '1:402862399682:ios:759990d2161205652c1b5b',
    messagingSenderId: '402862399682',
    projectId: 'uhmschoolbook',
    storageBucket: 'uhmschoolbook.appspot.com',
    iosBundleId: 'com.example.connectPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo32IrxGuT9PeplBjSLfpjBKb2cJ9wFls',
    appId: '1:402862399682:ios:b53f2256a99ef0ff2c1b5b',
    messagingSenderId: '402862399682',
    projectId: 'uhmschoolbook',
    storageBucket: 'uhmschoolbook.appspot.com',
    iosBundleId: 'com.example.connectPeople.RunnerTests',
  );
}
