// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagUMHxIOg_3xLgC8nebQX0RynKY94yp0',
    appId: '1:696735704101:web:c974eac126a324917c4bcc',
    messagingSenderId: '696735704101',
    projectId: 'uhmconnectpeople',
    authDomain: 'uhmconnectpeople.firebaseapp.com',
    storageBucket: 'uhmconnectpeople.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gC4VDuGRSgaL_gnG9lU-5HiGkATGL8c',
    appId: '1:696735704101:android:cadd67c775ed4d0e7c4bcc',
    messagingSenderId: '696735704101',
    projectId: 'uhmconnectpeople',
    storageBucket: 'uhmconnectpeople.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5xS35fDRCRY5kON4UepJVOYle9ZTQbQ',
    appId: '1:696735704101:ios:06fdf2cd2d1bfd7b7c4bcc',
    messagingSenderId: '696735704101',
    projectId: 'uhmconnectpeople',
    storageBucket: 'uhmconnectpeople.appspot.com',
    iosBundleId: 'com.example.connectPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC5xS35fDRCRY5kON4UepJVOYle9ZTQbQ',
    appId: '1:696735704101:ios:a06f68f0ac95942a7c4bcc',
    messagingSenderId: '696735704101',
    projectId: 'uhmconnectpeople',
    storageBucket: 'uhmconnectpeople.appspot.com',
    iosBundleId: 'com.example.connectPeople.RunnerTests',
  );
}
